requires:
  coffee: gulp-coffee
  concat: gulp-concat
  sourcemaps: gulp-sourcemaps
  plumber: gulp-plumber
  sass: gulp-sass
mimetypes:
  css:
    deps:
      - "sass"
    dev:
      outputFolder: "./test/dest"
      webPath: "/web"
      tasks:
        - { name: "plumber" }
        - { name: "sourcemaps.init" }
        - { name: "concat", args: "%filename%" }
        - { name: sourcemaps.write, args: "./test/dest" }
      htmlTag: "<script type='text/javascript' src='{{ asset('%path%') }}'></script>"
    files:
      concated.css:
        - "test/src/css/**/*.css"
  sass:
    dev:
      outputFolder: "./test/dest"
      webPath: "/web"
      tasks:
        - { name: "plumber" }
        - { name: "sass" }
    files:
      build.css:
        - "test/src/sass/test1.scss"
        - "test/src/sass/test10.scss"
  coffee:
    dev:
      outputFolder: "./test/dest"
      tasks:
        - { name: "coffee", args: { bare: true } }
    files:
      coffee.js:
        - "test/src/coffee/**/*.coffee"
  js:
    deps:
      - "coffee"
    dev:
      outputFolder: "./test/dest"
      webPath: "/web"
      tasks:
          - { name: "concat", args: "%filename%" }
    files:
      js.js:
        - "test/src/js/**/*.js"
        - "test/dest/coffee.js/**/*.js"
      test.js:
        - "test/src/test/some.js"
default:
  - css
  - js
replacementPaths:
  - "./test/templates/**/*.html"
